file_format: "1"
id: afternoon_breeze
name: Afternoon Breeze
type: shield
url: https://afternoonlabs.com/breeze/
requires:
  - pro_micro
features:
  - keys
siblings:
  - afternoon_breeze_left
  - afternoon_breeze_right
